### ISSUE TITLE
Iosevka no longer uses a makefile

### ISSUE THREAD

**Issue by rileyinman** [OJFord/iosevka-generate#4]
Since the release of Iosevka 2.0, the new build system uses npm and custom blocks in `build-plans.toml`. Most of the syntax is the same so that shouldn't be too hard to port, but it involves writing to a file instead of passing arguments to `make`.

**Comment by OJFord** [comment]
Many thanks, been meaning to come back to this, apologies for taking so long to see this issue.

Very grateful for a PR if you have a fix, otherwise I hope to revisit it soon. 🙂
