### ISSUE TITLE
Arch package seems to be broken

### ISSUE THREAD

**Issue by kauesena** [OJFord/iosevka-generate#9]
I ran 
```
 iosevka-generate ~/.config/iosevka/my-font.toml  
```
and in the end the message `Iosevka installed.` was printed, however, I cannot find the generated font files. They are neither in `~/.local/share/fonts`, nor in `/usr/share/fonts`.
I get three times the warnings:
```	
npm WARN iosevka@4.5.0 No repository field.
npm WARN iosevka@4.5.0 No license field.
```
Could you help me? I wonder if I should have downloaded some file from Iosevka's github page or if the recent update of the font to 4.5 broke something in the script.

**Comment by kauesena** [comment]
I managed to do it manually. It should be something to do with the package then.

**Comment by OJFord** [comment]
What do you mean by 'manually', what was it that worked?

**Comment by kauesena** [comment]
Sorry. I mean I followed the instructions [here](https://github.com/be5invis/Iosevka/#customized-build). And found the generated files inside `/dist` in the cloned github folder.

**Comment by OJFord** [comment]
Ah sorry I just replied to your AUR comment before realising this is the same, let's keep it here.

> in the end the message Iosevka installed. was printed

This just means the upstream Iosevka npm package was successfully installed, not your font (the wording could be better).

> I cannot find the generated font files. They are neither in ~/.local/share/fonts, nor in /usr/share/fonts.

Unless you've set `$XDG_DATA_HOME`, the would be in the former if successful, but it seems something went wrong. After `Iosevka installed` it should log `Loading font configurations in [...]`, did it not?

https://github.com/OJFord/iosevka-generate/blob/5071ac66b9deed19054d71a42ba60c8504ff63d4/iosevka-generate#L148-L149

> I get three times the warnings:

Those are from the Iosevka npm package.

**Comment by kauesena** [comment]
> Unless you've set $XDG_DATA_HOME, the would be in the former if successful, but it seems something went wrong. After Iosevka installed it should log Loading font configurations in [...], did it not?

No, it did not. I ran it again just to make sure. Here is the log just after running` iosevka-generate`:
```                                        
Updating https://github.com/be5invis/iosevka ...
Installing iosevka...
npm WARN iosevka@4.5.0 No repository field.
npm WARN iosevka@4.5.0 No license field.

audited 301 packages in 2.091s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN iosevka@4.5.0 No repository field.
npm WARN iosevka@4.5.0 No license field.

audited 301 packages in 1.406s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN iosevka@4.5.0 No repository field.
npm WARN iosevka@4.5.0 No license field.

up to date in 0.797s

18 packages are looking for funding
  run `npm fund` for details

fixed 0 of 0 vulnerabilities in 301 scanned packages
Iosevka installed.

```
The path to my build plan is `~/.config/iosevka/my-font.toml`.

**Comment by OJFord** [comment]
Ah, serves me right for looking at code on master rather than at the  release tag - I didn't release a version with TOML support yet, I wanted to use it a bit more on my own machine first but I sort of lost track of it, didn't mean to leave it so long.

I've pushed v0.3.1 now, level with master (so TOML etc. as described in the landing readme). Let me know if there's any further issue. Cheers.
